//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrect_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankMember()
        {
            this.MembersTransactionHistories = new HashSet<MembersTransactionHistory>();
        }
    
        public int ID { get; set; }
        public int BankID { get; set; }
        public int MemberID { get; set; }
        public string Acount { get; set; }
        public string AcountOwner { get; set; }
        public int IsActive { get; set; }
        public Nullable<System.DateTime> CraeteDate { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
        public virtual Member Member2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MembersTransactionHistory> MembersTransactionHistories { get; set; }
    }
}
