//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrect_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarImage
    {
        public int ID { get; set; }
        public int CarCustomerID { get; set; }
        public string Path { get; set; }
        public int IsActive { get; set; }
        public System.DateTime CraeteDate { get; set; }
    
        public virtual CarCustomer CarCustomer { get; set; }
    }
}
