//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrect_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.CarCustomers = new HashSet<CarCustomer>();
            this.CouponCustomers = new HashSet<CouponCustomer>();
            this.CustomerLocations = new HashSet<CustomerLocation>();
            this.CustomerOffices = new HashSet<CustomerOffice>();
            this.HistoryRankingPoints = new HashSet<HistoryRankingPoint>();
            this.OrderServices = new HashSet<OrderService>();
            this.ServiceBonusCustomers = new HashSet<ServiceBonusCustomer>();
            this.Members = new HashSet<Member>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Email { get; set; }
        public Nullable<int> Sex { get; set; }
        public string AvatarUrl { get; set; }
        public Nullable<int> ProvinceCode { get; set; }
        public Nullable<int> DistrictCode { get; set; }
        public string Address { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<int> QTYCancel { get; set; }
        public string RefCode { get; set; }
        public string MyRefCode { get; set; }
        public Nullable<int> CurrentCarID { get; set; }
        public int IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> CustomerRankID { get; set; }
        public Nullable<System.DateTime> RankDate { get; set; }
        public Nullable<int> RankingPoint { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarCustomer> CarCustomers { get; set; }
        public virtual CarCustomer CarCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CouponCustomer> CouponCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerLocation> CustomerLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOffice> CustomerOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryRankingPoint> HistoryRankingPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderService> OrderServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceBonusCustomer> ServiceBonusCustomers { get; set; }
        public virtual CustomerRank CustomerRank { get; set; }
        public virtual District District { get; set; }
        public virtual Province Province { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member> Members { get; set; }
    }
}
