//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrect_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerRank()
        {
            this.Customers = new HashSet<Customer>();
            this.CustomerRankServiceBonus = new HashSet<CustomerRankServiceBonu>();
            this.ServiceBonusCustomers = new HashSet<ServiceBonusCustomer>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string DescriptionEn { get; set; }
        public string DescriptionVi { get; set; }
        public string policyVN { get; set; }
        public string Policy { get; set; }
        public string OrtherGift { get; set; }
        public int ProfitCash { get; set; }
        public int ProfitVPN { get; set; }
        public int MinPoint { get; set; }
        public Nullable<int> MaxPoint { get; set; }
        public Nullable<int> PointBonus { get; set; }
        public Nullable<int> ProfitExtraBirthDay { get; set; }
        public Nullable<int> Level { get; set; }
        public int IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string TitleVi { get; set; }
        public string TitleEn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerRankServiceBonu> CustomerRankServiceBonus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceBonusCustomer> ServiceBonusCustomers { get; set; }
    }
}
