//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrect_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainServiceAdditionService
    {
        public int ID { get; set; }
        public int MainServiceID { get; set; }
        public int AdditionServiceID { get; set; }
        public int IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Service Service1 { get; set; }
        public virtual Service Service2 { get; set; }
        public virtual Service Service3 { get; set; }
        public virtual Service Service4 { get; set; }
        public virtual Service Service5 { get; set; }
        public virtual Service Service6 { get; set; }
        public virtual Service Service7 { get; set; }
        public virtual Service Service8 { get; set; }
    }
}
