//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrect_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembersTransactionHistory
    {
        public int ID { get; set; }
        public int MemberID { get; set; }
        public Nullable<int> OrderServiceID { get; set; }
        public Nullable<int> ProductOrderID { get; set; }
        public string ComboCode { get; set; }
        public Nullable<int> BankMemberID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int Point { get; set; }
        public int Type { get; set; }
        public int TransactionType { get; set; }
        public string TransactionID { get; set; }
        public int BeforeBalance { get; set; }
        public int AfterBalance { get; set; }
        public int Status { get; set; }
        public int IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public string Icon { get; set; }
        public Nullable<int> WalletID { get; set; }
        public string CodeVNPay { get; set; }
        public string KeyVNPay { get; set; }
        public Nullable<int> IsExtra { get; set; }
    
        public virtual BankMember BankMember { get; set; }
        public virtual Member Member { get; set; }
        public virtual OrderService OrderService { get; set; }
        public virtual ProductOrder ProductOrder { get; set; }
        public virtual Wallet Wallet { get; set; }
    }
}
