//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrect_Website.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarrectEntities : DbContext
    {
        public CarrectEntities()
            : base("name=CarrectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<AgentArea> AgentAreas { get; set; }
        public virtual DbSet<AgentImage> AgentImages { get; set; }
        public virtual DbSet<AppVersion> AppVersions { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<BankMember> BankMembers { get; set; }
        public virtual DbSet<CallQuality> CallQualities { get; set; }
        public virtual DbSet<CarBrand> CarBrands { get; set; }
        public virtual DbSet<CarCustomer> CarCustomers { get; set; }
        public virtual DbSet<CarImage> CarImages { get; set; }
        public virtual DbSet<CarModel> CarModels { get; set; }
        public virtual DbSet<CarSegment> CarSegments { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CategoryNew> CategoryNews { get; set; }
        public virtual DbSet<ClassShift> ClassShifts { get; set; }
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<ConfigCommission> ConfigCommissions { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<CouponCustomer> CouponCustomers { get; set; }
        public virtual DbSet<CouponWasher> CouponWashers { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerLocation> CustomerLocations { get; set; }
        public virtual DbSet<CustomerOffice> CustomerOffices { get; set; }
        public virtual DbSet<CustomerRank> CustomerRanks { get; set; }
        public virtual DbSet<CustomerRankServiceBonu> CustomerRankServiceBonus { get; set; }
        public virtual DbSet<Day> Days { get; set; }
        public virtual DbSet<DeviceHistoryLogin> DeviceHistoryLogins { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<HistoryRankingPoint> HistoryRankingPoints { get; set; }
        public virtual DbSet<Intro> Introes { get; set; }
        public virtual DbSet<MainServiceAdditionService> MainServiceAdditionServices { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MembersTransactionHistory> MembersTransactionHistories { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<OrderService> OrderServices { get; set; }
        public virtual DbSet<OrderServiceDetail> OrderServiceDetails { get; set; }
        public virtual DbSet<OrderServiceImage> OrderServiceImages { get; set; }
        public virtual DbSet<OrderServiceImageCar> OrderServiceImageCars { get; set; }
        public virtual DbSet<PaymentInstructionNote> PaymentInstructionNotes { get; set; }
        public virtual DbSet<Policy> Policies { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductImage> ProductImages { get; set; }
        public virtual DbSet<ProductOrder> ProductOrders { get; set; }
        public virtual DbSet<ProductOrderDetail> ProductOrderDetails { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<QA> QAs { get; set; }
        public virtual DbSet<QACustomer> QACustomers { get; set; }
        public virtual DbSet<Reason> Reasons { get; set; }
        public virtual DbSet<RequestForAdmin> RequestForAdmins { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServiceBonusCustomer> ServiceBonusCustomers { get; set; }
        public virtual DbSet<ServiceCombo> ServiceComboes { get; set; }
        public virtual DbSet<ServiceComboDetail> ServiceComboDetails { get; set; }
        public virtual DbSet<ServiceComboSegment> ServiceComboSegments { get; set; }
        public virtual DbSet<ServiceImage> ServiceImages { get; set; }
        public virtual DbSet<ServicePrice> ServicePrices { get; set; }
        public virtual DbSet<ServiceRequiteImage> ServiceRequiteImages { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Wallet> Wallets { get; set; }
    }
}
