//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrect_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderService()
        {
            this.MembersTransactionHistories = new HashSet<MembersTransactionHistory>();
            this.Notifications = new HashSet<Notification>();
            this.OrderServiceImages = new HashSet<OrderServiceImage>();
            this.OrderServiceDetails = new HashSet<OrderServiceDetail>();
            this.OrderServiceImageCars = new HashSet<OrderServiceImageCar>();
            this.RequestForAdmins = new HashSet<RequestForAdmin>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> AgentID { get; set; }
        public Nullable<int> FirstAgentID { get; set; }
        public string OrtherAgent { get; set; }
        public string AgentCancel { get; set; }
        public Nullable<int> CarCustomerID { get; set; }
        public int BookingNow { get; set; }
        public int IsInDoor { get; set; }
        public int Status { get; set; }
        public int IsActive { get; set; }
        public int TotalPrice { get; set; }
        public int BasePrice { get; set; }
        public Nullable<int> CouponPoint { get; set; }
        public Nullable<int> UsePoint { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<int> CouponID { get; set; }
        public string Reason { get; set; }
        public string Note { get; set; }
        public string NoteRate { get; set; }
        public string ReasonAgentCancel { get; set; }
        public Nullable<int> IsRate { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<int> StatusPayment { get; set; }
        public Nullable<int> TotalEstTime { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.DateTime> EstBookingDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public Nullable<int> ComboPrice { get; set; }
        public Nullable<int> ServiceComboSegmentID { get; set; }
        public string CodeCombo { get; set; }
        public string ReasonCancel { get; set; }
        public string CarNote { get; set; }
        public string ParkNote { get; set; }
        public string PlaceID { get; set; }
        public string Address { get; set; }
        public Nullable<int> IsPushFirst { get; set; }
        public Nullable<int> MemberCancel { get; set; }
        public Nullable<int> UserCancel { get; set; }
        public Nullable<int> IsExportVAT { get; set; }
        public Nullable<int> MainDiscount { get; set; }
        public Nullable<int> MainBasePrice { get; set; }
        public Nullable<int> MainPrice { get; set; }
        public Nullable<int> ExtraPaymentType { get; set; }
        public Nullable<int> ExtraDiscount { get; set; }
        public Nullable<int> ExtraBasePrice { get; set; }
        public Nullable<int> ExtraPrice { get; set; }
        public Nullable<int> OfficeID { get; set; }
        public Nullable<int> BonusVAT { get; set; }
        public string WasherNote { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Area Area { get; set; }
        public virtual CarCustomer CarCustomer { get; set; }
        public virtual Coupon Coupon { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual CustomerOffice CustomerOffice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MembersTransactionHistory> MembersTransactionHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderServiceImage> OrderServiceImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderServiceDetail> OrderServiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderServiceImageCar> OrderServiceImageCars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestForAdmin> RequestForAdmins { get; set; }
        public virtual ServiceComboSegment ServiceComboSegment { get; set; }
    }
}
