//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrect_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderServiceDetail
    {
        public int ID { get; set; }
        public int OrderItemID { get; set; }
        public int ServiceDetailID { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> EstTime { get; set; }
        public int IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> IsFree { get; set; }
        public Nullable<int> IsPayment { get; set; }
        public Nullable<int> IsExtra { get; set; }
    
        public virtual OrderService OrderService { get; set; }
        public virtual ServicePrice ServicePrice { get; set; }
    }
}
