//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrect_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductOrder()
        {
            this.MembersTransactionHistories = new HashSet<MembersTransactionHistory>();
            this.Notifications = new HashSet<Notification>();
            this.ProductOrderDetails = new HashSet<ProductOrderDetail>();
        }
    
        public int ID { get; set; }
        public int Status { get; set; }
        public int TotalPrice { get; set; }
        public int AgentID { get; set; }
        public Nullable<int> DepositPoint { get; set; }
        public Nullable<int> ProfitPoint { get; set; }
        public string Note { get; set; }
        public int IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Code { get; set; }
        public Nullable<int> CouponID { get; set; }
        public Nullable<int> BasePrice { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Coupon Coupon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MembersTransactionHistory> MembersTransactionHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOrderDetail> ProductOrderDetails { get; set; }
    }
}
