//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrect_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrderDetail
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int ProductOrderID { get; set; }
        public int QTY { get; set; }
        public int Price { get; set; }
        public int IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductOrder ProductOrder { get; set; }
    }
}
