//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrect_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reason
    {
        public int ID { get; set; }
        public string ContentVN { get; set; }
        public string ContentEN { get; set; }
        public Nullable<int> Type { get; set; }
        public int IsActive { get; set; }
        public Nullable<System.DateTime> CraeteDate { get; set; }
    }
}
