//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrect_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceBonusCustomer
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int RankID { get; set; }
        public int ServiceID { get; set; }
        public System.DateTime ExpriceTime { get; set; }
        public int Status { get; set; }
        public int Type { get; set; }
        public Nullable<System.DateTime> UseDate { get; set; }
        public int IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual CustomerRank CustomerRank { get; set; }
        public virtual Service Service { get; set; }
    }
}
