//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrect_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.CustomerRankServiceBonus = new HashSet<CustomerRankServiceBonu>();
            this.MainServiceAdditionServices = new HashSet<MainServiceAdditionService>();
            this.MainServiceAdditionServices1 = new HashSet<MainServiceAdditionService>();
            this.MainServiceAdditionServices2 = new HashSet<MainServiceAdditionService>();
            this.MainServiceAdditionServices3 = new HashSet<MainServiceAdditionService>();
            this.MainServiceAdditionServices4 = new HashSet<MainServiceAdditionService>();
            this.MainServiceAdditionServices5 = new HashSet<MainServiceAdditionService>();
            this.MainServiceAdditionServices6 = new HashSet<MainServiceAdditionService>();
            this.MainServiceAdditionServices7 = new HashSet<MainServiceAdditionService>();
            this.MainServiceAdditionServices8 = new HashSet<MainServiceAdditionService>();
            this.ServiceBonusCustomers = new HashSet<ServiceBonusCustomer>();
            this.ServiceRequiteImages = new HashSet<ServiceRequiteImage>();
            this.ServicePrices = new HashSet<ServicePrice>();
            this.ServiceComboDetails = new HashSet<ServiceComboDetail>();
            this.ServiceImages = new HashSet<ServiceImage>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string NameVN { get; set; }
        public string NameEN { get; set; }
        public string Icon { get; set; }
        public string Description { get; set; }
        public int Type { get; set; }
        public Nullable<int> OrderDisplay { get; set; }
        public int IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string DescriptionEN { get; set; }
        public string Color { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerRankServiceBonu> CustomerRankServiceBonus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainServiceAdditionService> MainServiceAdditionServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainServiceAdditionService> MainServiceAdditionServices1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainServiceAdditionService> MainServiceAdditionServices2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainServiceAdditionService> MainServiceAdditionServices3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainServiceAdditionService> MainServiceAdditionServices4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainServiceAdditionService> MainServiceAdditionServices5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainServiceAdditionService> MainServiceAdditionServices6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainServiceAdditionService> MainServiceAdditionServices7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainServiceAdditionService> MainServiceAdditionServices8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceBonusCustomer> ServiceBonusCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequiteImage> ServiceRequiteImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePrice> ServicePrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceComboDetail> ServiceComboDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceImage> ServiceImages { get; set; }
    }
}
