//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrect_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCombo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceCombo()
        {
            this.ServiceComboSegments = new HashSet<ServiceComboSegment>();
            this.ServiceComboDetails = new HashSet<ServiceComboDetail>();
            this.ServiceImages = new HashSet<ServiceImage>();
        }
    
        public int ID { get; set; }
        public string ComboCode { get; set; }
        public string NameVN { get; set; }
        public string NameEN { get; set; }
        public string icon { get; set; }
        public string Depcription { get; set; }
        public int IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string DescriptionEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceComboSegment> ServiceComboSegments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceComboDetail> ServiceComboDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceImage> ServiceImages { get; set; }
    }
}
