//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrect_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicePrice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServicePrice()
        {
            this.OrderServiceDetails = new HashSet<OrderServiceDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public int CarSegmentID { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> BasePrice { get; set; }
        public Nullable<int> Discount { get; set; }
        public string Code { get; set; }
        public Nullable<int> EstTime { get; set; }
        public int IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Name { get; set; }
        public Nullable<double> USDBasePrice { get; set; }
        public Nullable<double> USDPrice { get; set; }
    
        public virtual CarSegment CarSegment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderServiceDetail> OrderServiceDetails { get; set; }
        public virtual Service Service { get; set; }
    }
}
