//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrect_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceComboDetail
    {
        public int ID { get; set; }
        public int ServiceID { get; set; }
        public int ServiceComboID { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public int IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual ServiceCombo ServiceCombo { get; set; }
    }
}
